blogs/urls.py
from django.urls import path
from . import views

app_name = 'blogs'

urlpatterns = [
    path('', views.allblogs , name='allblogs'),
    path('<int:blog_id>/',views.detail , name='detail')
]

jobs/urls.py
from django.urls import path
from . import views

app_name = 'jobs'

urlpatterns = [
    path('', views.index , name='jobs'),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings

from jobs import views as job
from blogs import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('jobs/', include('jobs.urls')),
    path('blogs/', include('blogs.urls')),
    path('', job.index),
]


urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blogs/models.py
from django.db import models


from datetime import datetime

# Create your models here.


class Blog(models.Model):
	title = models.CharField(max_length=200)
	image = models.ImageField(upload_to='blog/%Y/%m/%d/')
	body = models.TextField()
	pub_date = models.DateTimeField()


	def __str__(self):
		return self.title


	def summary(self):
		return self.body[:80] + '....'

jobs/models.py
from django.db import models


from datetime import datetime

# Create your models here.


class Job(models.Model):
	image = models.ImageField(upload_to='photos/%Y/%m/%d/')
	summary = models.CharField(max_length=200)


	# def __str__(self):
	# 	return self.name

blogs/views.py
from django.shortcuts import render , get_object_or_404

from .models import Blog

# Create your views here.
def allblogs(request):
	blogs = Blog.objects.all
	return render(request , 'blogs/allblogs.html',{'blogs': blogs})

def detail(request , blog_id):
	detail_blog = get_object_or_404(Blog,pk=blog_id)
	return render(request , 'blogs/detail.html',{'blog': detail_blog})

jobs/views.py
from django.shortcuts import render
from .models import Job
# Create your views here.
def index(request):
	jobs = Job.objects
	context = {
       'jobs': jobs
	}
	return render(request , 'jobs/home.html',context)

blogs/templates/blogs/allblogs.html
{% load staticfiles %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Album example · Bootstrap</title>

    <!-- Bootstrap core CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

  </head>
  <body>

  <!-- Navbar -->
  {% include 'partials/_navbar.html' %}

<main role="main">

  <section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">Welcome To My Blog</h1>
      <p class="lead text-muted">Hey My name is Mahmudul.I love To Make Web Applications.
      My Favourite Languages Are PHP,Python,JavaScript</p>
      <p>
        <a href="mailto:mahmudul.hassan240@gmail.com" class="btn btn-primary my-2">Email Me</a>

      </p>
      <img src="{% static 'images.jpg' %}" alt="">
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row">

        {% for blog in blogs %}
          <div class="card mb-4">
            <img class="card-img-top" src="{{blog.image.url}}" alt="Card image cap">
            <div class="card-body">
              <h2 class="card-title">{{blog.title}}</h2>
              <p class="card-text">{{blog.summary}}</p>
              <a href="{% url "blogs:detail" blog.id %}" class="btn btn-primary">Read More &rarr;</a>
            </div>
            <div class="card-footer text-muted">
              Posted on {{blog.pub_date}} by
              <a href="#">Start Bootstrap</a>
            </div>
          </div>
        {% endfor %}


      </div>
    </div>
  </div>

</main>


  <!-- Footer -->
  {% include 'partials/_footer.html' %}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>


</body>
</html>

blogs/templates/blogs/detail.html
{% load staticfiles %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Album example · Bootstrap</title>

    <!-- Bootstrap core CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

  </head>
  <body>

  <!-- Navbar -->
  {% include 'partials/_navbar.html' %}

<main role="main">

  <section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">Welcome To My Blog</h1>
      <p class="lead text-muted">Hey My name is Mahmudul.I love To Make Web Applications.
      My Favourite Languages Are PHP,Python,JavaScript</p>
      <p>
        <a href="mailto:mahmudul.hassan240@gmail.com" class="btn btn-primary my-2">Email Me</a>

      </p>
      <img src="{% static 'images.jpg' %}" alt="">
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row">

         <div class="col-md-8 mx-auto">
          <div class="card mb-4">
            <img class="card-img-top" src="{{blog.image.url}}" alt="Card image cap">
            <div class="card-body">
              <h2 class="card-title">{{blog.title}}</h2>
              <p class="card-text">{{blog.body}}</p>

            </div>
            <div class="card-footer text-muted">
              Posted on {{blog.pub_date}} by
              <a href="#">Start Bootstrap</a>
            </div>
          </div>

        </div>

      </div>
    </div>
  </div>

</main>


  <!-- Footer -->
  {% include 'partials/_footer.html' %}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>


</body>
</html>

blogs/templates/partials/_footer.html
<footer class="text-muted">
  <div class="container">
    <p class="text-center">
      &copy Mahmudul Hassan {% now "Y" %}

    </p>
    <p class="float-right">
    	<a href="#">Back to top</a>
    </p>

  </div>
</footer>

blogs/templates/partials/_navbar.html
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <ul class="list-unstyled">
            <li><a href="#" class="text-white">Follow on Twitter</a></li>
            <li><a href="#" class="text-white">Like on Facebook</a></li>
            <li><a href="#" class="text-white">Email me</a></li>
          </ul>
        </div>

      </div>
      <div class="row">
        <div class="col-sm-12">
          <ul class="nav">
            <li class="nav-item">
              <h4 class="text-white"><a class="nav-link" href="#">Resume</a></h4>
            </li>
            <li class="nav-item">
              <h4 class="text-white"><a class="nav-link" href="{% url "blogs:allblogs" %}">Blog</a></h4>
            </li>


          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container d-flex justify-content-between">
      <a href="#" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2" focusable="false" aria-hidden="true"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
        <strong>Mahmudul Hassan</strong>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

jobs/templates/jobs/home.html
{% load staticfiles %}
<!doctype html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Mahmudul</title>

    <!-- Bootstrap core CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

  </head>
  <body>

  <!-- Navbar -->
  {% include 'partials/_navbar.html' %}

<main role="main">

  <section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">Hi, I'm Mahmudul</h1>
      <p class="lead text-muted">Hey My name is Mahmudul.I love To Make Web Applications.
      My Favourite Languages Are PHP,Python,JavaScript</p>
      <p>
        <a href="mailto:mahmudul.hassan240@gmail.com" class="btn btn-primary my-2">Email Me</a>


      </p>
      <img src="{% static 'images.jpg' %}" alt="">
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row">

        {% for job in jobs.all %}
            <div class="col-md-4">
              <div class="card mb-4 shadow-sm">
                <img class="card-img-top img-thumbnail img-responsive" src="{{job.image.url}}" alt="">
                <div class="card-body">
                  <p class="card-text">{{job.summary}}</p>

                </div>
              </div>
            </div>
        {% endfor %}


      </div>
    </div>
  </div>

</main>


  <!-- Footer -->
  {% include 'partials/_footer.html' %}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>


</body>
</html>

jobs/templates/partials/_footer.html
<footer class="text-muted">
  <div class="container">
    <p class="text-center">
      &copy Mahmudul Hassan {% now "Y" %}

    </p>
    <p class="float-right">
    	<a href="#">Back to top</a>
    </p>

  </div>
</footer>

jobs/templates/partials/_navbar.html
{% load staticfiles %}
<header>

  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <ul class="list-unstyled">
            <li><a href="#" class="text-white">Follow on Twitter</a></li>
            <li><a href="#" class="text-white">Like on Facebook</a></li>
            <li><a href="mailto:mahmudul.hassan240@gmail.com" class="text-white">Email me</a></li>
          </ul>
        </div>

      </div>
      <div class="row">
        <div class="col-sm-12">
          <ul class="nav">
            <li class="nav-item">
              <h4 class="text-white"><a class="nav-link" href="{% static 'dummy.pdf' %}">Resume</a></h4>
            </li>
            <li class="nav-item">
              <h4 class="text-white"><a class="nav-link" href="{% url "blogs:allblogs" %}">Blog</a></h4>
            </li>

            <li class="nav-item">
              <h4 class="text-white"><a class="nav-link" href="{% url "jobs:jobs" %}">Home</a></h4>
            </li>

          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container d-flex justify-content-between">
      <a href="{% url "jobs:jobs" %}" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2" focusable="false" aria-hidden="true"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
        <strong>Mahmudul Hassan</strong>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>